version: '3'
services:
  rambler:
    build:
      context: ./rambler
    depends_on:
      - postgres
    environment:
      RAMBLER_DRIVER: postgresql
      RAMBLER_PROTOCOL: tcp
      RAMBLER_USER: postgres
      RAMBLER_PASSWORD: password
      RAMBLER_HOST: postgres
      RAMBLER_PORT: 5432
      RAMBLER_DATABASE: rocketplate
      RAMBLER_DIRECTORY: migrations
      RAMBLER_TABLE: migrations

  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rocketplate
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/dev-config:/etc/prometheus

  prometheus-assets:
    image: tuckerconnelly/prometheus-assets
    ports:
      - "3002:3000"
    environment:
      ASSETS_METRIC_NAME: web

  postgres-exporter:
    image: wrouesnel/postgres_exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: postgres://postgres:password@postgres:5432/rocketplate?sslmode=disable
      PG_EXPORTER_EXTEND_QUERY_PATH: /etc/postgres_exporter/queries.yaml
    volumes:
      - ./postgres-exporter:/etc/postgres_exporter

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./prometheus/dev-config:/etc/alertmanager/

  postgres-grafana:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grafana
    ports:
      - "5433:5432"

  grafana:
    build:
      context: ./grafana
    ports:
      - "3003:3000"
    environment:
      GF_DATABASE_URL: postgres://postgres:password@postgres-grafana:5432/grafana
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    depends_on:
      - postgres-grafana
      - prometheus
    volumes:
      - ./grafana/dev-provisioning:/etc/grafana/provisioning

  phppgadmin:
    image: dockage/phppgadmin
    ports:
      - "3004:80"
    environment:
      PHP_PG_ADMIN_SERVER_HOST: postgres
      PHP_PG_ADMIN_SERVER_DEFAULT_DB: rocketplate
