version: '3'
services:
  rambler:
    build:
      context: ./rambler
    depends_on:
      - postgres
    environment:
      RAMBLER_DRIVER: postgresql
      RAMBLER_PROTOCOL: tcp
      RAMBLER_USER: postgres
      RAMBLER_PASSWORD: password
      RAMBLER_HOST: postgres
      RAMBLER_PORT: 5432
      RAMBLER_DATABASE: rocketplate
      RAMBLER_DIRECTORY: migrations
      RAMBLER_TABLE: migrations

  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rocketplate
    ports:
      - "5432:5432"

  prometheus:
    build:
      context: ./prometheus
    ports:
      - "9090:9090"

  prometheus-assets:
    image: tuckerconnelly/prometheus-assets
    ports:
      - "3002:3000"

  postgres-grafana:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grafana
    ports:
      - "5433:5432"

  grafana:
    build:
      context: ./grafana
    ports:
      - "3003:3000"
    environment:
      GF_DATABASE_URL: postgres://postgres:password@docker.for.mac.localhost:5433/grafana
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    depends_on:
      - postgres-grafana
      - prometheus
