kubeStateMetrics:
  service:
    clusterIP: ""

alertmanagerFiles:
  alertmanager.yml:
    global:
      slack_api_url: ${ALERTS_SLACK_WEBHOOK_URL}

    route:
      receiver: slack

    receivers:
      - name: slack
        slack_configs:
          - channel: ${ALERTS_SLACK_CHANNEL}
            title: 500 on home page
            actions:
              - type: button
                text: Roll back to last deployment
                # Lol, definitely change this
                url: https://google.com

serverFiles:
  alerts:
    groups:
      - name: postgres
        rules:
          - alert: PostgresDown
            expr: pg_up == 0
            for: 5m
            labels:
              severity: page
            annotations:
              summary: 'Postgres is down'

  prometheus.yml:
    rule_files:
      - /etc/config/rules
      - /etc/config/alerts
    scrape_configs:
      - job_name: postgres
        static_configs:
          - targets: [${PG_EXPORTER_HOST}]

      - job_name: api
        static_configs:
          - targets: [${API_EXPORTER_HOST}]

      - job_name: web
        static_configs:
          - targets: [${PROMETHEUS_ASSETS_EXPORTER_HOST}]
        params:
          url: [${WEB_URL}]

      - job_name: nginx-ingress
        static_configs:
          - targets: [${NGINX_INGRESS_EXPORTER_HOST}]

      - job_name: kubernetes-nodes
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/$1/proxy/metrics

      - job_name: kube-state-metrics
        static_configs:
          - targets: ["prometheus-kube-state-metrics:80"]
