# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/${PROJECT_ID}/rocketplate', '.']
- name: 'gcr.io/${PROJECT_ID}/rocketplate'
  args: ['version']
- name: 'gcr.io/${PROJECT_ID}/rocketplate'
  entrypoint: 'bash'
  args:
    - '-c'
    - 'docker version'
- name: 'gcr.io/${PROJECT_ID}/rocketplate'
  entrypoint: 'bash'
  args:
    - '-c'
    - 'ls -al /usr/local/bin'
- name: 'gcr.io/${PROJECT_ID}/rocketplate'
  entrypoint: 'bash'
  args:
    - '-c'
    - 'docker-compose version'
images: ['gcr.io/${PROJECT_ID}/rocketplate:latest']
